### ISSUE TITLE
I'm not sure purging the object outright is working

### ISSUE THREAD

**Issue by axfelix** [discoverygarden/islandora_owner_permissions#3]
Because the full "manage" menu isn't available to regular authenticated users, I don't see a way to use the "purge" On Own Object Permission that's enabled by this module. Otherwise the other functionality appears to work great, though!

**Comment by willtp87** [comment]
Hi,

I'm going to close this as it is being handled through other communication channels. The README has been updated with further information that should help folks in the future.

Thanks,
William Panting
